config/routes.rb
Rails.application.routes.draw do

  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}



  namespace :admin do
    get 'homes/top'
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, except: :destroy
    resources :orders, only: [:show, :update]
end

scope module: "public" do
root :to => "homes#top"
get "about" => "homes#about"
resources :registration, only: [:new, :create]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  
end

app/models/order.rb
class Order < ApplicationRecord
  enum status:{クレジットカード: 0,銀行振込:1}
  enum status:{入金待ち: 0,入金確認:1,製作中:2,発送準備中:3, 発送済み:4}
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum status:{製作不可: 0,製作待ち:1,製作中:2,製作完了:3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to genre_index_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  @orders = Order.all
  @customer = Customer.find(params[:id])
  end

  private
  def customer_params
    params.require(:customer).permit(:first_name, :last_name)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
def new
  @item = Item.new
end

def create
  @item = Item.new(item_params)
  if @item.save
      redirect_to admin_items_path
  else
      render new_admin_item_path
  end
end

def index
  @items = Item.all
end

def show
  @item = Item.find(params[:id])
end

def edit
  @item = Item.find(params[:id])
end

def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_item_path(@item.id)
end




  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, 
:first_name_kana, :last_name_kana,:email, :postal_code, :address, :telephone_number])
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<h2>ジャンル編集</h2>
<%= form_with model: @genre do |f| %>
<label for="name">ジャンル名</label>
<%= f.text_field :name %>
<%= f.submit "変更を保存" %>
<% end %>

app/views/admin/genres/index.html.erb
<h2>ジャンル一覧・追加</h2>
  <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
<p>ジャンル名</p>
<%= f.text_field :name %>
<%= f.submit "新規登録", class:"btn btn-success" %>
<% end %>
<table>
  <thead>
    <tr>
    <th>ジャンル</th>
    </tr>
  </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
          <td><%= genre.name %></td>
          <td><%= link_to '編集する', edit_admin_genre_path(genre.id), class:"btn btn-success" %></td>
          </tr>
        <% end %>
      </tbody>
</table>

app/views/admin/items/edit.html.erb
<h2>商品編集</h2>
<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
<p>商品画像</p>
<%= f.file_field :image, accept: "image/*" %>
<p>商品名</p>
<%= f.text_field :name %>
<p>商品説明</p>
<%= f.text_area :introduction %>
<p>ジャンル</p>
<%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "選択して下さい" %>
<p>税抜価格</p>
<%= f.text_field :price %> 円
<p>販売ステータス</p>
<%= f.radio_button :is_active, true %>
<%= f.label :is_active, '販売中' %>
<%= f.radio_button :is_active, false %>
<%= f.label :is_active, '販売停止中' %>
<%= f.submit "変更を保存", class:"btn btn-success" %>
<% end %>

app/views/admin/items/index.html.erb
        <h2>商品一覧</h2>
        <table>
            <thead>
                <tr>
                    <th>商品ID</th>
                    <th>商品名</th>
                    <th>税抜価格</th>
                    <th>ジャンル</th>
                    <th>ステータス</th>
                </tr>
            </thead>

            <tbody>
            <% @items.each do |item| %>
            <tr>
                <td><%= item.id %></td>
                <td><%= item.name %></td>
                <td><%= item.price %>円</td>
                <td><%= item.genre.name %></td>
            <% if item.is_active %>
                <td>販売中</td>
            <% else %>
                <td>販売停止中</td>
            <% end %>
            </tr>
            <% end %>
            </tbody>
        </table>

app/views/admin/items/new.html.erb
<h2>商品新規登録</h2>
<%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
<p>商品画像</p>
<%= f.file_field :image, accept: "image/*" %>
<p>商品名</p>
<%= f.text_field :name %>
<p>商品説明</p>
<%= f.text_area :introduction %>
<p>ジャンル</p>
<%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "選択して下さい" %>
<p>税抜価格</p>
<%= f.text_field :price %> 円
<p>販売ステータス</p>
<%= f.radio_button :is_active, true %>
<%= f.label :is_active, '販売中', value: true %>
<%= f.radio_button :is_active, false %>
<%= f.label :is_active, '販売停止中', value: false %>
<%= f.submit "新規登録", class:"btn btn-success" %>
<% end %>

app/views/admin/items/show.html.erb
<!--なぜIDになるの？　インデックスも含めて。-->

<h2>商品詳細</h2>
      <td><%= image_tag @item.get_sweets_image(100,100) %></td>

      <table>
      <tbody>
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td>
            <%= @item.introduction %>
          </td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td>
            <%= @item.genre_id %>
          </td>
        </tr>
        <tr>
          <td>
            <p>税込価格</p>
            <p>(税抜価格)</p>
          </td>
          <td>
            <span>(<%= @item.add_tax_price.to_s(:delimited) %>) 円</span>
            <span><%= @item.price.to_s(:delimited) %></span>
          </td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active == true %>
            	<span>販売中</span>
      			<% else %>
  	    			<span>販売停止中</span>
  		    	<% end %>
  		    </td>
        </tr>
        <tr>
          <td>
            <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
          </td>
        </tr>
      </tbody>
      </table>

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>